name: Build Alexandria
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build_application:
      permissions:
        contents: write
      strategy:
        fail-fast: false
        matrix:
          platform: [windows-latest, ubuntu-20.04, macos-latest] # [macos-latest, ubuntu-20.04, windows-latest]
      runs-on: ${{ matrix.platform }}
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: 'recursive'
        - name: setup node
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: install Rust stable
          uses: dtolnay/rust-toolchain@stable
        - name: install dependencies (ubuntu only)
          if: matrix.platform == 'ubuntu-20.04'
          run: |
            sudo apt-get update
            sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
            sudo apt-get install -y clang autoconf libtool
            cd ./libmobi-rs && sh build-linux.sh
        - name: install dependencies (macOS only)
          if: matrix.platform == 'macos-latest'
          run: |
            brew install automake autoconf libtool
            cd ./libmobi-rs && sh build-mac.sh
        - name: install frontend dependencies
          run: npm install # change this to npm or pnpm depending on which one you use
        - uses: tauri-apps/tauri-action@v0
        - name: Archive production artifacts
          uses: actions/upload-artifact@v3
          with:
            name: Upload Binaries
            path: |
              src-tauri/target/release/**/*.exe
              src-tauri/target/release/**/*.msi
              src-tauri/target/release/**/*.deb
              src-tauri/target/release/**/*.AppImage
              src-tauri/target/release/**/*.dmg
              !src-tauri/target/release/deps
              !src-tauri/target/release/build